### PR TITLE
ci | diagnostics report...

### PR DESCRIPTION
**Pull request by kepocnhh**

### CODE REVIEW

**Comment by kepocnhh** [comment]
Test multiline comment: 1640296704

**Comment by kepocnhh** [comment]
Test multiline comment: 1640297267:
 - line #1

**Comment by kepocnhh** [comment]
Test multiline comment: 1640297386:
 - line #1

**Comment by kepocnhh** [comment]
Test multiline comment: 1640297519:%0A - line #1

**Comment by kepocnhh** [comment]
Test multiline comment: 1640297602:
 - line #1

**Comment by continuousi** [comment]
Closed by GitHub build [#34](https://github.com/StanleyProjects/AndroidExtension.UserInterface/actions/runs/1617239262):n - due to code style issues. See the [report](https://StanleyProjects.github.io/AndroidExtension.UserInterface/build/34/1617239262/diagnostics/report/CODE_STYLE/index.html).

**Comment by kepocnhh** [comment]
Test multiline comment: 1640298300[foo](https://github.com)::
 - line [#1](https://github.com/StanleyProjects)

**Comment by kepocnhh** [comment]
Closed by GitHub pretender build [#101](https://github.com/StanleyProjects/AndroidExtension.UserInterface/actions/runs/1640354921):
 - due to code style issues -> [report](https://StanleyProjects.github.io/AndroidExtension.UserInterface/build/101/1640354921/diagnostics/report/CODE_STYLE/index.html)

**Comment by kepocnhh** [comment]
Closed by GitHub pretender build [#101](https://github.com/StanleyProjects/AndroidExtension.UserInterface/actions/runs/1640355993):
 - due to code style issues -> [report](https://StanleyProjects.github.io/AndroidExtension.UserInterface/build/101/1640355993/diagnostics/report/CODE_STYLE/index.html)

**Comment by continuousi** [comment]
Closed by GitHub build [#35](https://github.com/StanleyProjects/AndroidExtension.UserInterface/actions/runs/1619450616):n - due to code style issues -> [report](https://StanleyProjects.github.io/AndroidExtension.UserInterface/build/35/1619450616/diagnostics/report/CODE_STYLE/index.html)

**Comment by kepocnhh** [comment]
Closed by GitHub pretender build [#101](https://github.com/StanleyProjects/AndroidExtension.UserInterface/actions/runs/1640356584):%0A - due to code style issues -> [report](https://StanleyProjects.github.io/AndroidExtension.UserInterface/build/101/1640356584/diagnostics/report/CODE_STYLE/index.html)

**Comment by kepocnhh** [comment]
Closed by GitHub pretender build [#101](https://github.com/StanleyProjects/AndroidExtension.UserInterface/actions/runs/1640356647):%0A - due to code style issues -> [report](https://StanleyProjects.github.io/AndroidExtension.UserInterface/build/101/1640356647/diagnostics/report/CODE_STYLE/index.html)

**Comment by kepocnhh** [comment]
Closed by GitHub pretender build [#101](https://github.com/StanleyProjects/AndroidExtension.UserInterface/actions/runs/1640356966):
 - due to code style issues -> [report](https://StanleyProjects.github.io/AndroidExtension.UserInterface/build/101/1640356966/diagnostics/report/CODE_STYLE/index.html)

**Comment by continuousi** [comment]
First line [#36](https://github.com/StanleyProjects/AndroidExtension.UserInterface/actions/runs/1619488969):
 - second line

**Pull request closed without merging**
